# Generated by Django 6.0.2 on 2026-04-30 12:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', message='Número de teléfono inválido')])),
                ('status', models.CharField(choices=[('waiting', 'esperando'), ('offered', 'ofrecido'), ('booked', 'agendado'), ('expired', 'expirado')], default='waiting', max_length=50)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entry', to='reservas.business')),
                ('offered_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.resourceslot')),
            ],
        ),
    ]
