# Generated by Django 5.2.8 on 2025-11-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetemplate',
            name='end_time',
            field=models.TimeField(help_text='Fecha y hora de finalización'),
        ),
    ]
