# Generated by Django 5.2.8 on 2025-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pendiente'), ('confirmed', 'confirmado'), ('cancelled', 'cancelado')], default='pending', max_length=20),
        ),
    ]
