# Generated by Django 5.2.8 on 2025-11-12 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_resourcetemplate_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackOutDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=30, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='reservas.business')),
            ],
            options={
                'verbose_name': 'Blackout date',
                'verbose_name_plural': 'Blackout dates',
                'ordering': ['business', 'date'],
            },
        ),
    ]
