# Generated by Django 5.2.8 on 2025-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_blackoutdates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackoutdates',
            options={'ordering': ['business', 'start_date'], 'verbose_name': 'Blackout date', 'verbose_name_plural': 'Blackout dates'},
        ),
        migrations.RenameField(
            model_name='blackoutdates',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='blackoutdates',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
